// -----------------------------------------------------------------------------
// (c) balarabe@protonmail.com                                      License: MIT
// :v: 2018-05-24 13:36:58 349F26                    [zr-web/media_type_test.go]
// -----------------------------------------------------------------------------

package web

// Test_mime_MediaTypes_
// Test_mime_MediaType

/*
to test all items in media_type.go use:
    go test --run Test_mime_

to generate a test coverage report for the whole module use:
    go test -coverprofile cover.out
    go tool cover -html=cover.out
*/

import (
	"testing"

	"github.com/balacode/zr"
)

// go test --run Test_mime_MediaTypes_
func Test_mime_MediaTypes_(t *testing.T) {
	zr.TBegin(t)
	if len(MediaTypes) != len(expectMediaTypes) {
		zr.TFail(t,
			`MediaTypes has `, len(MediaTypes), ` items.`,
			` must have `, len(expectMediaTypes), ` items.`,
		)
	}
	for i, itm := range MediaTypes {
		if itm != expectMediaTypes[i] {
			zr.TFail(t, `MediaTypes has `, len(MediaTypes), ` items.`,
				` must have `, len(expectMediaTypes), ` items.`,
			)
		}
	}
} //                                                       Test_mime_MediaTypes_

// go test --run Test_mime_MediaType_
func Test_mime_MediaType_(t *testing.T) {
	zr.TBegin(t)
	// MediaType_(name string) string
	//
	/*
		name = Trim(str.ToLower(name), zr.SPACES)
		if i := str.LastIndex(name, "."); i != -1 {
			name = str.ToLower(name[i+1:])
		}
		for _, iter := range MediaTypes {
			if name == iter.ext || name == iter.mimeType {
				return iter.mimeType
			}
		}
		return ""
	*/
} //                                                        Test_mime_MediaType_

var expectMediaTypes = []struct {
	ext      string
	mimeType string
}{
	// commonest MIME types:
	{"htm", "text/html"},             // 01
	{"html", "text/html"},            // 02
	{"css", "text/css"},              // 03
	{"js", "application/javascript"}, // 04
	{"json", "application/json"},     // 05
	{"ico", "image/x-icon"},          // 06
	{"png", "image/png"},             // 07
	{"jpg", "image/jpeg"},            // 08
	{"jpeg", "image/jpeg"},           // 09
	{"svg", "image/svg+xml"},         // 10
	{"gif", "image/gif"},             // 11
	{"xml", "application/xml"},       // 12
	//
	// other common MIME types:
	{"bmp", "image/x-ms-bmp"},
	{"es", "application/ecmascript"},
	{"jpe", "image/jpeg"},
	{"pdf", "application/pdf"},
	{"svgz", "image/svg+xml"},
	{"txt", "text/plain"},
	{"xhtml", "application/xhtml+xml"},
	{"xls", "application/vnd.ms-excel"},
	{"xlt", "application/vnd.ms-excel"},
	{"zip", "application/zip"},
	//
	// audio/video MIME types:
	{"3gp", "video/3gpp"},
	{"asf", "video/x-ms-asf"},
	{"asx", "video/x-ms-asf"},
	{"avi", "video/x-msvideo"},
	{"flv", "video/x-flv"},
	{"mid", "audio/midi"},
	{"midi", "audio/midi"},
	{"mov", "video/quicktime"},
	{"mp4", "video/mp4"},
	{"mpe", "video/mpeg"},
	{"mpeg", "video/mpeg"},
	{"mpg", "video/mpeg"},
	{"ogg", "audio/ogg"},
	{"wav", "audio/x-wav"},
	{"wm", "video/x-ms-wm"},
	{"wma", "audio/x-ms-wma"},
	{"wmv", "video/x-ms-wmv"},
	{"wmx", "video/x-ms-wmx"},
	{"wvx", "video/x-ms-wvx"},
	//
	// text:
	{"323", "text/h323"},
	{"asc", "text/plain"},
	{"bib", "text/x-bibtex"},
	{"boo", "text/x-boo"},
	{"brf", "text/plain"},
	{"c", "text/x-csrc"},
	{"c++", "text/x-c++src"},
	{"cc", "text/x-c++src"},
	{"cls", "text/x-tex"},
	{"cpp", "text/x-c++src"},
	{"csh", "text/x-csh"},
	{"csv", "text/csv"},
	{"cxx", "text/x-c++src"},
	{"d", "text/x-dsrc"},
	{"diff", "text/x-diff"},
	{"etx", "text/x-setext"},
	{"gcd", "text/x-pcs-gcd"},
	{"h", "text/x-chdr"},
	{"h++", "text/x-c++hdr"},
	{"hh", "text/x-c++hdr"},
	{"hpp", "text/x-c++hdr"},
	{"hs", "text/x-haskell"},
	{"htc", "text/x-component"},
	{"hxx", "text/x-c++hdr"},
	{"ics", "text/calendar"},
	{"icz", "text/calendar"},
	{"jad", "text/vnd.sun.j2me.app-descriptor"},
	{"java", "text/x-java"},
	{"lhs", "text/x-literate-haskell"},
	{"ltx", "text/x-tex"},
	{"manifest", "text/cache-manifest"},
	{"mml", "text/mathml"},
	{"moc", "text/x-moc"},
	{"p", "text/x-pascal"},
	{"pas", "text/x-pascal"},
	{"patch", "text/x-diff"},
	{"pl", "text/x-perl"},
	{"pm", "text/x-perl"},
	{"pot", "text/plain"},
	{"py", "text/x-python"},
	{"rtx", "text/richtext"},
	{"scala", "text/x-scala"},
	{"sct", "text/scriptlet"},
	{"sh", "text/x-sh"},
	{"shtml", "text/html"},
	{"sty", "text/x-tex"},
	{"tcl", "text/x-tcl"},
	{"tex", "text/x-tex"},
	{"text", "text/plain"},
	{"tk", "text/x-tcl"},
	{"tm", "text/texmacs"},
	{"ts", "text/texmacs"},
	{"tsv", "text/tab-separated-values"},
	{"uls", "text/iuls"},
	{"vcf", "text/x-vcard"},
	{"vcs", "text/x-vcalendar"},
	{"wml", "text/vnd.wap.wml"},
	{"wmls", "text/vnd.wap.wmlscript"},
	{"wsc", "text/scriptlet"},
	//
	// image:
	{"art", "image/x-jg"},
	{"cdr", "image/x-coreldraw"},
	{"cdt", "image/x-coreldrawtemplate"},
	{"cpt", "image/x-corelphotopaint"},
	{"cr2", "image/x-canon-cr2"},
	{"crw", "image/x-canon-crw"},
	{"djv", "image/vnd.djvu"},
	{"djvu", "image/vnd.djvu"},
	{"erf", "image/x-epson-erf"},
	{"ief", "image/ief"},
	{"jng", "image/x-jng"},
	{"nef", "image/x-nikon-nef"},
	{"orf", "image/x-olympus-orf"},
	{"pat", "image/x-coreldrawpattern"},
	{"pbm", "image/x-portable-bitmap"},
	{"pcx", "image/pcx"},
	{"pgm", "image/x-portable-graymap"},
	{"pnm", "image/x-portable-anymap"},
	{"ppm", "image/x-portable-pixmap"},
	{"psd", "image/x-photoshop"},
	{"ras", "image/x-cmu-raster"},
	{"rgb", "image/x-rgb"},
	{"tif", "image/tiff"},
	{"tiff", "image/tiff"},
	{"wbmp", "image/vnd.wap.wbmp"},
	{"xbm", "image/x-xbitmap"},
	{"xpm", "image/x-xpixmap"},
	{"xwd", "image/x-xwindowdump"},
	//
	// application:
	{"docx", "application/vnd.openxmlformats-officedocument" +
		".wordprocessingml.document"},
	{"dotx", "application/vnd.openxmlformats-officedocument" +
		".wordprocessingml.template"},
	{"potx", "application/vnd.openxmlformats-officedocument" +
		".presentationml.template"},
	{"ppsx", "application/vnd.openxmlformats-officedocument" +
		".presentationml.slideshow"},
	{"pptx", "application/vnd.openxmlformats-officedocument" +
		".presentationml.presentation"},
	{"xlsx", "application/vnd.openxmlformats-officedocument" +
		".spreadsheetml.sheet"},
	{"xltx", "application/vnd.openxmlformats-officedocument" +
		".spreadsheetml.template"},
	{"%", "application/x-trash"},
	{"7z", "application/x-7z-compressed"},
	{"abw", "application/x-abiword"},
	{"ai", "application/postscript"},
	{"anx", "application/annodex"},
	{"apk", "application/vnd.android.package-archive"},
	{"atom", "application/atom+xml"},
	{"atomcat", "application/atomcat+xml"},
	{"atomsrv", "application/atomserv+xml"},
	{"bak", "application/x-trash"},
	{"bat", "application/x-msdos-program"},
	{"bcpio", "application/x-bcpio"},
	{"bin", "application/octet-stream"},
	{"book", "application/x-maker"},
	{"cab", "application/x-cab"},
	{"cap", "application/cap"},
	{"cat", "application/vnd.ms-pki.seccat"},
	{"cbr", "application/x-cbr"},
	{"cbz", "application/x-cbz"},
	{"cda", "application/x-cdf"},
	{"cdf", "application/x-cdf"},
	{"cdy", "application/vnd.cinderella"},
	{"chrt", "application/x-kchart"},
	{"class", "application/java-vm"},
	{"cod", "application/vnd.rim.cod"},
	{"com", "application/x-msdos-program"},
	{"cpio", "application/x-cpio"},
	{"cpt", "application/mac-compactpro"},
	{"crl", "application/x-pkcs7-crl"},
	{"crt", "application/x-x509-ca-cert"},
	{"csh", "application/x-csh"},
	{"cu", "application/cu-seeme"},
	{"dat", "application/x-ns-proxy-autoconfig"},
	{"davmount", "application/davmount+xml"},
	{"dcr", "application/x-director"},
	{"deb", "application/x-debian-package"},
	{"dir", "application/x-director"},
	{"dll", "application/x-msdos-program"},
	{"dmg", "application/x-apple-diskimage"},
	{"dms", "application/x-dms"},
	{"doc", "application/msword"},
	{"dot", "application/msword"},
	{"dvi", "application/x-dvi"},
	{"dxr", "application/x-director"},
	{"eps", "application/postscript"},
	{"eps2", "application/postscript"},
	{"eps3", "application/postscript"},
	{"epsf", "application/postscript"},
	{"epsi", "application/postscript"},
	{"exe", "application/x-msdos-program"},
	{"ez", "application/andrew-inset"},
	{"fb", "application/x-maker"},
	{"fbdoc", "application/x-maker"},
	{"fig", "application/x-xfig"},
	{"fm", "application/x-maker"},
	{"frame", "application/x-maker"},
	{"frm", "application/x-maker"},
	{"gcf", "application/x-graphing-calculator"},
	{"gf", "application/x-tex-gf"},
	{"gnumeric", "application/x-gnumeric"},
	{"gsf", "application/x-font"},
	{"gtar", "application/x-gtar"},
	{"hdf", "application/x-hdf"},
	{"hqx", "application/mac-binhex40"},
	{"hta", "application/hta"},
	{"ica", "application/x-ica"},
	{"iii", "application/x-iphone"},
	{"info", "application/x-info"},
	{"ins", "application/x-internet-signup"},
	{"iso", "application/x-iso9660-image"},
	{"isp", "application/x-internet-signup"},
	{"jam", "application/x-jam"},
	{"jar", "application/java-archive"},
	{"jmz", "application/x-jmol"},
	{"jnlp", "application/x-java-jnlp-file"},
	{"key", "application/pgp-keys"},
	{"kil", "application/x-killustrator"},
	{"kml", "application/vnd.google-earth.kml+xml"},
	{"kmz", "application/vnd.google-earth.kmz"},
	{"kpr", "application/x-kpresenter"},
	{"kpt", "application/x-kpresenter"},
	{"ksp", "application/x-kspread"},
	{"kwd", "application/x-kword"},
	{"kwt", "application/x-kword"},
	{"latex", "application/x-latex"},
	{"lha", "application/x-lha"},
	{"lin", "application/bbolin"},
	{"lyx", "application/x-lyx"},
	{"lzh", "application/x-lzh"},
	{"lzx", "application/x-lzx"},
	{"m3g", "application/m3g"},
	{"maker", "application/x-maker"},
	{"man", "application/x-troff-man"},
	{"mdb", "application/msaccess"},
	{"me", "application/x-troff-me"},
	{"mif", "application/x-mif"},
	{"mm", "application/x-freemind"},
	{"mmf", "application/vnd.smaf"},
	{"ms", "application/x-troff-ms"},
	{"msi", "application/x-msi"},
	{"mxf", "application/mxf"},
	{"nb", "application/mathematica"},
	{"nbp", "application/mathematica"},
	{"nc", "application/x-netcdf"},
	{"nwc", "application/x-nwc"},
	{"o", "application/x-object"},
	{"oda", "application/oda"},
	{"ogx", "application/ogg"},
	{"old", "application/x-trash"},
	{"oza", "application/x-oz-application"},
	{"p7r", "application/x-pkcs7-certreqresp"},
	{"pac", "application/x-ns-proxy-autoconfig"},
	{"pcap", "application/cap"},
	{"pcf", "application/x-font"},
	{"pcf.Z", "application/x-font"},
	{"pfa", "application/x-font"},
	{"pfb", "application/x-font"},
	{"pgn", "application/x-mfc_chess-pgn"},
	{"pgp", "application/pgp-signature"},
	{"php", "application/x-httpd-php"},
	{"php3", "application/x-httpd-php3"},
	{"php3p", "application/x-httpd-php3-preprocessed"},
	{"php4", "application/x-httpd-php4"},
	{"php5", "application/x-httpd-php5"},
	{"phps", "application/x-httpd-php-source"},
	{"pht", "application/x-httpd-php"},
	{"phtml", "application/x-httpd-php"},
	{"pk", "application/x-tex-pk"},
	{"pps", "application/vnd.ms-powerpoint"},
	{"ppt", "application/vnd.ms-powerpoint"},
	{"prf", "application/pics-rules"},
	{"ps", "application/postscript"},
	{"pyc", "application/x-python-code"},
	{"pyo", "application/x-python-code"},
	{"qgs", "application/x-qgis"},
	{"qtl", "application/x-quicktimeplayer"},
	{"rar", "application/rar"},
	{"rb", "application/x-ruby"},
	{"rdf", "application/rdf+xml"},
	{"rhtml", "application/x-httpd-eruby"},
	{"roff", "application/x-troff"},
	{"rpm", "application/x-redhat-package-manager"},
	{"rss", "application/rss+xml"},
	{"rtf", "application/rtf"},
	{"scr", "application/x-silverlight"},
	{"sda", "application/vnd.stardivision.draw"},
	{"sdc", "application/vnd.stardivision.calc"},
	{"sdd", "application/vnd.stardivision.impress"},
	{"sdf", "application/vnd.stardivision.math"},
	{"sds", "application/vnd.stardivision.chart"},
	{"sdw", "application/vnd.stardivision.writer"},
	{"ser", "application/java-serialized-object"},
	{"sgf", "application/x-go-sgf"},
	{"sgl", "application/vnd.stardivision.writer-global"},
	{"sh", "application/x-sh"},
	{"shar", "application/x-shar"},
	{"shp", "application/x-qgis"},
	{"shx", "application/x-qgis"},
	{"sik", "application/x-trash"},
	{"sis", "application/vnd.symbian.install"},
	{"sit", "application/x-stuffit"},
	{"sitx", "application/x-stuffit"},
	{"skd", "application/x-koan"},
	{"skm", "application/x-koan"},
	{"skp", "application/x-koan"},
	{"skt", "application/x-koan"},
	{"smi", "application/smil"},
	{"smil", "application/smil"},
	{"spl", "application/futuresplash"},
	{"spl", "application/x-futuresplash"},
	{"src", "application/x-wais-source"},
	{"stc", "application/vnd.sun.xml.calc.template"},
	{"std", "application/vnd.sun.xml.draw.template"},
	{"sti", "application/vnd.sun.xml.impress.template"},
	{"stl", "application/vnd.ms-pki.stl"},
	{"stw", "application/vnd.sun.xml.writer.template"},
	{"sv4cpio", "application/x-sv4cpio"},
	{"sv4crc", "application/x-sv4crc"},
	{"swf", "application/x-shockwave-flash"},
	{"swfl", "application/x-shockwave-flash"},
	{"sxc", "application/vnd.sun.xml.calc"},
	{"sxd", "application/vnd.sun.xml.draw"},
	{"sxg", "application/vnd.sun.xml.writer.global"},
	{"sxi", "application/vnd.sun.xml.impress"},
	{"sxm", "application/vnd.sun.xml.math"},
	{"sxw", "application/vnd.sun.xml.writer"},
	{"t", "application/x-troff"},
	{"tar", "application/x-tar"},
	{"taz", "application/x-gtar"},
	{"tcl", "application/x-tcl"},
	{"texi", "application/x-texinfo"},
	{"texinfo", "application/x-texinfo"},
	{"tgz", "application/x-gtar"},
	{"torrent", "application/x-bittorrent"},
	{"tr", "application/x-troff"},
	{"tsp", "application/dsptype"},
	{"ttf", "application/x-font"},
	{"udeb", "application/x-debian-package"},
	{"ustar", "application/x-ustar"},
	{"vcd", "application/x-cdlink"},
	{"vsd", "application/vnd.visio"},
	{"wad", "application/x-doom"},
	{"wbxml", "application/vnd.wap.wbxml"},
	{"wk", "application/x-123"},
	{"wmd", "application/x-ms-wmd"},
	{"wmlc", "application/vnd.wap.wmlc"},
	{"wmlsc", "application/vnd.wap.wmlscriptc"},
	{"wmz", "application/x-ms-wmz"},
	{"wp5", "application/vnd.wordperfect5.1"},
	{"wpd", "application/vnd.wordperfect"},
	{"wz", "application/x-wingz"},
	{"xcf", "application/x-xcf"},
	{"xht", "application/xhtml+xml"},
	{"xlb", "application/vnd.ms-excel"},
	{"xpi", "application/x-xpinstall"},
	{"xsd", "application/xml"},
	{"xsl", "application/xml"},
	{"xspf", "application/xspf+xml"},
	{"xul", "application/vnd.mozilla.xul+xml"},
	{"~", "application/x-trash"},
	{"db", "application/vnd.oasis.opendocument" +
		".database"},
	{"dc", "application/vnd.oasis.opendocument" +
		".chart"},
	{"odf", "application/vnd.oasis.opendocument" +
		".formula"},
	{"odg", "application/vnd.oasis.opendocument" +
		".graphics"},
	{"odi", "application/vnd.oasis.opendocument" +
		".image"},
	{"odm", "application/vnd.oasis.opendocument" +
		".text-master"},
	{"odp", "application/vnd.oasis.opendocument" +
		".presentation"},
	{"ods", "application/vnd.oasis.opendocument" +
		".spreadsheet"},
	{"odt", "application/vnd.oasis.opendocument" +
		".text"},
	{"otg", "application/vnd.oasis.opendocument" +
		".graphics-template"},
	{"oth", "application/vnd.oasis.opendocument" +
		".text-web"},
	{"otp", "application/vnd.oasis.opendocument" +
		".presentation-template"},
	{"ots", "application/vnd.oasis.opendocument" +
		".spreadsheet-template"},
	{"ott", "application/vnd.oasis.opendocument" +
		".text-template"},
	//
	// audio:
	{"aif", "audio/x-aiff"},
	{"aifc", "audio/x-aiff"},
	{"aiff", "audio/x-aiff"},
	{"amr", "audio/amr"},
	{"au", "audio/basic"},
	{"awb", "audio/amr-wb"},
	{"axa", "audio/annodex"},
	{"flac", "audio/flac"},
	{"gsm", "audio/x-gsm"},
	{"kar", "audio/midi"},
	{"m3u", "audio/mpegurl"},
	{"m3u", "audio/x-mpegurl"},
	{"m4a", "audio/mpeg"},
	{"mp2", "audio/mpeg"},
	{"mp3", "audio/mpeg"},
	{"mpega", "audio/mpeg"},
	{"mpga", "audio/mpeg"},
	{"oga", "audio/ogg"},
	{"pls", "audio/x-scpls"},
	{"ra", "audio/x-pn-realaudio"},
	{"ra", "audio/x-realaudio"},
	{"ram", "audio/x-pn-realaudio"},
	{"rm", "audio/x-pn-realaudio"},
	{"sd2", "audio/x-sd2"},
	{"sid", "audio/prs.sid"},
	{"snd", "audio/basic"},
	{"spx", "audio/ogg"},
	{"wax", "audio/x-ms-wax"},
	//
	// video:
	{"axv", "video/annodex"},
	{"dif", "video/dv"},
	{"dl", "video/dl"},
	{"dv", "video/dv"},
	{"fli", "video/fli"},
	{"gl", "video/gl"},
	{"lsf", "video/x-la-asf"},
	{"lsx", "video/x-la-asf"},
	{"mkv", "video/x-matroska"},
	{"mng", "video/x-mng"},
	{"movie", "video/x-sgi-movie"},
	{"mpv", "video/x-matroska"},
	{"mxu", "video/vnd.mpegurl"},
	{"ogv", "video/ogg"},
	{"qt", "video/quicktime"},
	//
	// model:
	{"iges", "model/iges"},
	{"igs", "model/iges"},
	{"mesh", "model/mesh"},
	{"msh", "model/mesh"},
	{"silo", "model/mesh"},
	{"vrml", "model/vrml"},
	{"wrl", "model/vrml"},
	{"x3d", "model/x3d+xml"},
	{"x3db", "model/x3d+binary"},
	{"x3dv", "model/x3d+vrml"},
	//
	// world:
	{"vrm", "x-world/x-vrml"},
	{"vrml", "x-world/x-vrml"},
	{"wrl", "x-world/x-vrml"},
	//
	// etc:
	{"eml", "message/rfc822"},
	{"ice", "x-conference/x-cooltalk"},
	{"sisx", "x-epoc/x-sisx-app"},
	//
	// chemical:
	{"alc", "chemical/x-alchemy"},
	{"asn", "chemical/x-ncbi-asn1"},
	{"asn", "chemical/x-ncbi-asn1-spec"},
	{"aso", "chemical/x-ncbi-asn1-binary"},
	{"b", "chemical/x-molconn-Z"},
	{"bsd", "chemical/x-crossfire"},
	{"c3d", "chemical/x-chem3d"},
	{"cac", "chemical/x-cache"},
	{"cache", "chemical/x-cache"},
	{"cascii", "chemical/x-cactvs-binary"},
	{"cbin", "chemical/x-cactvs-binary"},
	{"cdx", "chemical/x-cdx"},
	{"cef", "chemical/x-cxf"},
	{"cer", "chemical/x-cerius"},
	{"chm", "chemical/x-chemdraw"},
	{"cif", "chemical/x-cif"},
	{"cmdf", "chemical/x-cmdf"},
	{"cml", "chemical/x-cml"},
	{"cpa", "chemical/x-compass"},
	{"csf", "chemical/x-cache-csf"},
	{"csm", "chemical/x-csml"},
	{"csml", "chemical/x-csml"},
	{"ctab", "chemical/x-cactvs-binary"},
	{"ctx", "chemical/x-ctx"},
	{"cub", "chemical/x-gaussian-cube"},
	{"cxf", "chemical/x-cxf"},
	{"dx", "chemical/x-jcamp-dx"},
	{"emb", "chemical/x-embl-dl-nucleotide"},
	{"embl", "chemical/x-embl-dl-nucleotide"},
	{"ent", "chemical/x-ncbi-asn1-ascii"},
	{"ent", "chemical/x-pdb"},
	{"fch", "chemical/x-gaussian-checkpoint"},
	{"fchk", "chemical/x-gaussian-checkpoint"},
	{"gal", "chemical/x-gaussian-log"},
	{"gam", "chemical/x-gamess-input"},
	{"gamin", "chemical/x-gamess-input"},
	{"gau", "chemical/x-gaussian-input"},
	{"gcg", "chemical/x-gcg8-sequence"},
	{"gen", "chemical/x-genbank"},
	{"gjc", "chemical/x-gaussian-input"},
	{"gjf", "chemical/x-gaussian-input"},
	{"gpt", "chemical/x-mopac-graph"},
	{"hin", "chemical/x-hin"},
	{"inp", "chemical/x-gamess-input"},
	{"ist", "chemical/x-isostar"},
	{"istr", "chemical/x-isostar"},
	{"jdx", "chemical/x-jcamp-dx"},
	{"kin", "chemical/x-kinemage"},
	{"mcif", "chemical/x-mmcif"},
	{"mcm", "chemical/x-macmolecule"},
	{"mif", "#chemical/x-mif"},
	{"mmd", "chemical/x-macromodel-input"},
	{"mmod", "chemical/x-macromodel-input"},
	{"mol", "chemical/x-mdl-molfile"},
	{"mol2", "chemical/x-mol2"},
	{"moo", "chemical/x-mopac-out"},
	{"mop", "chemical/x-mopac-input"},
	{"mopcrt", "chemical/x-mopac-input"},
	{"mpc", "chemical/x-mopac-input"},
	{"mvb", "chemical/x-mopac-vib"},
	{"pc", "chemical/x-galactic-pc"},
	{"pdb", "chemical/x-pdb"},
	{"prt", "chemical/x-ncbi-asn1-ascii"},
	{"rd", "chemical/x-mdl-rdfile"},
	{"ros", "chemical/x-rosdal"},
	{"rxn", "chemical/x-mdl-rxnfile"},
	{"sd", "chemical/x-mdl-sdfile"},
	{"sdf", "chemical/x-mdl-sdfile"},
	{"smi", "#chemical/x-daylight-smiles"},
	{"sw", "chemical/x-swissprot"},
	{"tgf", "chemical/x-mdl-tgf"},
	{"val", "chemical/x-ncbi-asn1-binary"},
	{"vmd", "chemical/x-vmd"},
	{"vms", "chemical/x-vamas-iso14976"},
	{"xtel", "chemical/x-xtel"},
	{"xyz", "chemical/x-xyz"},
	{"zmt", "chemical/x-mopac-input"},
} //                                                            expectMediaTypes

//end
